### DISCUSSION TITLE
"Permission denied" when running opensafely locally

### DISCUSSION THREAD

**Discussion by inglesp** [opensafely/documentation#128] [Q&A] [answered]
I've just tried `opensafely run` locally for the first time, and I'm getting a `Permission denied` error.

```
$ opensafely run produce_breakdown

Running actions: produce_breakdown

jobrunner.run loop started
produce_breakdown: Preparing
produce_breakdown: Copying in code from /home/inglesp/work/ebmdatalab/opensafely/research/imd-breakdown
produce_breakdown: Copying input file generate_study_population: output/input.csv
produce_breakdown: Started
produce_breakdown: View live logs using: docker logs -f job-imd-breakdown-produce-breakdown-chpoalvro7oqt7f7
produce_breakdown: Running
produce_breakdown: Finished, checking status and extracting outputs
produce_breakdown: Logs written to: /home/inglesp/work/ebmdatalab/opensafely/research/imd-breakdown/metadata/produce_breakdown.log
produce_breakdown: Job exited with an error code
produce_breakdown: Cleaning up container and volume

=> produce_breakdown
   Job exited with an error code

   log file: metadata/produce_breakdown.log
   outputs:
     (no outputs)

   logs:

     [FATAL tini (7)] exec analysis/breakdown.py failed: Permission denied
```

Here's my project.yaml:

```
version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  produce_breakdown:
    run: python:latest analysis/breakdown.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: output/breakdown.csv
```

It's not clear what I'm doing wrong.  Any ideas?
