### DISCUSSION TITLE
create a `run_all` type action for a subset of actions

### DISCUSSION THREAD

**Discussion by wjchulme** [opensafely/documentation#155] [Q&A] [answered]
Is it possible to create an action that will run a set of earlier actions? In the same way that `run_all` does, except not for all actions.

It's not too useful on the job server because you can easily click all the relevant actions, but when running locally via `opensafely run`, often there is a set of actions that should be run together, but they each have to be run separately which can be a bit of a pain.

**Comment by wjchulme** [comment, marked as answer]
Before the `run_all` action was a built-in feature of `openssafely run`, it was defined explicitly in the `project.yaml` as follows:

```yaml
  run_all:
    needs: [run_model, extract_data]
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml
```

This could be re-purposed -- just put all the relevant actions in the `needs:` section. You still need to have the action itself _do_ something, hence the `cohortextractor:latest --version`. And since each action also needs to output something, the `whatever: project.yaml` is also necessary, but ignorable.
