### DISCUSSION TITLE
Github test error: --study-definition: invalid choice: 'study_definition'

### DISCUSSION THREAD

**Discussion by annaschultze** [opensafely/documentation#164] [Q&A] [answered]
The below action runs fine locally, and generates an input csv based on the file `study_definition.py. ` However, on github tests it fails with the error `cohortextractor generate_cohort: error: argument --study-definition: invalid choice: 'study_definition' (choose from 'all', 'study_definition_measures')` . Any ideas what I might be doing wrong? 

```
actions:
generate_cohort_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-02-01" 
  outputs:
      highly_sensitive:
        cohort: output/input_2019-02-01.csv
```
