### DISCUSSION TITLE
Getting started guide - difficulty making the histogram

### DISCUSSION THREAD

**Discussion by Miriam-S-git** [opensafely/documentation#296] [Q&A] [answered]
HI.  A very basic learner here.  So apologies if I have missed something basic.  
I am getting stuck on making the histogram.
" add a chart" 

The following command in the command line just continues to generate the csv file and doesn't get to the next step of the histogram.  opensafely run run_all --force-run-dependencies 

I have pasted all the other commands from the tutorial into the files.  

I suspect I have made a basic error.  But can't pinpoint what it is. 

I've added a screen shot of the end point of the this command when I run it.  

Thank you for your help. 

<img width="1280" alt="Screenshot 2021-06-26 at 17 43 46" src="https://user-images.githubusercontent.com/74236842/123520138-209d6300-d6a7-11eb-977f-86d547b0ff4e.png">

**Comment by StevenMaude** [comment, marked as answer]
Hi @Miriam-S-git :wave:

Thanks for your question!

The `describe` part in your file is at the same level as `actions`. In fact, the `describe` part goes under `actions`, because `describe` *is* an action, e.g.

```yaml
version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  describe:
    run: python:latest python analysis/report.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/descriptive.png
```

(I had to look for a minute here. The problem here is actually a little bit subtle because there is no error! Your slightly incorrect `project.yaml` file is still treated as a valid file by the opensafely command! However, when you run `opensafely`, `opensafely` doesn't recognise the `describe` action you just added!)

Please let us know if this change fixes your problem :slightly_smiling_face:

Or equally if it doesn't, and we can help you figure this out, so that you can complete the tutorial!
