### DISCUSSION TITLE
Date formats when providing your own dummy data

### DISCUSSION THREAD

**Discussion by elsie-h** [opensafely/documentation#499] [Q&A] [answered]
I'm creating my own dummy data using [this R script](https://github.com/opensafely/covid-ve-change-over-time/blob/update-dummy-data/analysis/dummy_data_vax.R) and am trying to run it using the following action:

```
  generate_study_population_vax:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vax --output-format feather
    dummy_data_file: analysis/lib/dummy_data_vax.feather
    needs: 
    - design
    outputs:
      highly_sensitive:
        cohort: output/input_vax.feather
```

However, when I include date variables, I'm getting the following error:

```
if query_args["date_format"] == "YYYY":
     KeyError: 'date_format'
```

I get the same error when using csv as the output format. 

I assume I need to convert the date-time strings to a different class in R before writing to feather format (or csv)? I've tried `as.POSIXct(.x)`, `as.Date(.x)`, `as.Date(as.character(.x)` ([as done here](https://github.com/opensafely/comparative-ve-research/blob/80579b369386ea0ca5e396334b7a5e04db33fadd/analysis/dummy/data_makedummy.R#L291)), and just `as.character(.x)`, but all result in the above error.
