### DISCUSSION TITLE
No output issue when generating measures

### DISCUSSION THREAD

**Discussion by markagreen** [opensafely/documentation#590] [Q&A] [answered]
I am following the tutorial on my local machine trying to generate sample code for trends in hospitalisations and deaths using OpenSAFELY. I have been going through the [Measures](https://docs.opensafely.org/measures/) tutorial as this appears the most appropriate way to go about getting monthly values. Using the tutorial as my example, and copying the code into [my repository here](https://github.com/markagreen/healthcare_disruption_openSAFELY), I have some difficulty getting the code to actually run locally. Specifically, I am currently getting the following error message:

=> generate_measures
   No outputs found matching patterns:
    - output/measures/measure_*.csv

   Did you mean to match one of these files instead?
    - analysis/.RData
    - analysis/.Rhistory
    - analysis/.Rproj.user/2551CBB9/pcs/files-pane.pper
    - analysis/.Rproj.user/2551CBB9/pcs/source-pane.pper
    - analysis/.Rproj.user/2551CBB9/pcs/windowlayoutstate.pper
    - analysis/.Rproj.user/2551CBB9/pcs/workbench-pane.pper
    - analysis/.Rproj.user/2551CBB9/rmd-outputs
    - analysis/.Rproj.user/2551CBB9/saved_source_markers
    - analysis/.Rproj.user/2551CBB9/sources/per/t/1E008F3B
    - analysis/.Rproj.user/2551CBB9/sources/per/t/1E008F3B-contents
    - analysis/.Rproj.user/2551CBB9/sources/per/t/4713036A
    - analysis/.Rproj.user/2551CBB9/sources/per/t/4713036A-contents
    - analysis/.Rproj.user/2551CBB9/sources/prop/136A632E
    - analysis/analysis.Rproj
    - analysis/study_definition.py
    - project.yaml

   log file: metadata/generate_measures.log
   outputs:
     (no outputs)

I may assume the issue is because it is expecting the files to exist to write to, but as this is the first time running the code it is not the case. It might be something else of course and I am probably being a dingbat here. Any suggestions would be most welcome.

**Comment by StevenMaude** [comment]
@markagreen: :wave: It looks like the specified paths under `outputs` in your `project.yaml` are slightly inconsistent with the `output-dir`; easily done!

The project runs for me without error if I amend [these lines of the `project.yaml`](https://github.com/markagreen/healthcare_disruption_openSAFELY/blob/b7e6430408d75672146d5f5ee943f40999f792e2/project.yaml#L25-L36) to:

```yaml
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2022-02-01 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv
```

To highlight the changes:

```diff
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2022-02-01 by month" --skip-existing --output-dir=output/measures --output-format=csv.gz
    outputs:
      highly_sensitive:
-       cohort: output/input_*.csv.gz
+       cohort: output/measures/input_*.csv.gz

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
-        measure_csv: output/measure_*.csv
+        measure_csv: output/measures/measure_*.csv
```

I think that should get your project working, but if not, let us know! :smiley:
